app.py
import os
from flask import Flask, render_template
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

def create_app():
    app = Flask(__name__,static_folder="estatico")
    app.register_blueprint(pages)
    client= MongoClient(os.environ.get("MONGODB_URI"))
    app.db=client.fpblog
    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('not-found.html'), 404
    return app

routes.py
import os
import datetime as dt
import uuid
from flask import Blueprint, current_app, render_template, request, redirect, url_for
from pymongo import MongoClient

pages = Blueprint("habits",__name__,template_folder="templates",static_folder="estatico")


@pages.context_processor
def add_defs():
    def date_range(start: dt.datetime):
        dates=[start + dt.timedelta(days=diff) for diff in range(-3, 4)]
        return dates
    return {"date_range": date_range}

def date_midn(date: dt.datetime):
    nova=date.replace(hour=0,minute=0,second=0,microsecond=0)
    return nova

@pages.route("/")
def habitos():
    
    date_str=request.args.get("date")
    if date_str:
        selected_date=dt.datetime.fromisoformat(date_str)
    else:
        selected_date=date_midn(dt.datetime.today())
    habits_on_date=[habit 
                    for habit in current_app.db.posts.find({"Ad_data":{"$lte":selected_date}})]
    completions=[habit['habit'] 
                    for habit in current_app.db.completions.find({"date":str(selected_date)})]
    return render_template("habits.html",
                            title="Habit Tracker",
                            habits=habits_on_date,
                            selected_date=selected_date,
                            completions=completions)

@pages.route("/add", methods=["GET","POST"])
def novohabito():
    if request.method == "POST":
        habito=request.form.get("habit")
        date=date_midn(dt.datetime.today())
        current_app.db.posts.insert_one({"_id":uuid.uuid4().hex,
                                    "Nome":habito,
                                    "Ad_data":date,
                                    "Ativo":True})
    date=date_midn(dt.datetime.today())
    return render_template("add.html",
                            title="Habit Tracker - Add",
                            selected_date=date)

@pages.route("/complete", methods=["POST"])
def complete():
    if request.method == "POST":
        date=request.form.get("date")
        habit=request.form.get("habitId")
        current_app.db.completions.insert_one({"date":date,
                                                "habit":habit})
        
    return redirect(url_for('habits.habitos',date=date))

@pages.route("/drop", methods=["POST","GET"])
def deletahabito():
    date=date_midn(dt.datetime.today())
    habits=[habit for habit in current_app.db.posts.find({"Ativo":True})]
    todel = [habit['habit'] for habit in current_app.db.dropped.find({})]
    if request.method == "POST":
        drop=request.form.get("habitId")
        situation=request.form.get("confirmation")
        if situation == "U":
            current_app.db.dropped.insert_one({'habit':drop})
            todel = [habit['habit'] for habit in current_app.db.dropped.find({})]
        elif situation =="S":
            current_app.db.dropped.delete_one({'habit':drop})
            todel = [habit['habit'] for habit in current_app.db.dropped.find({})]
        else:
            todel = [habit['habit'] for habit in current_app.db.dropped.find({})]
            for deletar in todel:
                current_app.db.posts.update_one({"_id":deletar},{"$set":{"Ativo":False}})
            current_app.db.dropped.delete_many({})
            habits=[habit for habit in current_app.db.posts.find({"Ativo":True})]
            
    return render_template("drop.html",
                            title="Habit Tracker - Drop",
                            habits=habits,
                            dropped=todel,
                            selected_date=date)

templates/add.html
{% extends 'base.html'%}
{% import 'macros.jinja2' as macros%}

{%block content%}
    <form class="form" method="POST">
        <textarea class="form__input" id="habit" name="habit" row ="3" placeholder="Add new daily habit"></textarea>
        <button class="form__button" type="submit">Add</button>
    </form>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
    <title>{{ title or "Todos"}}</title>
    <link rel="stylesheet" href="{{url_for('static',filename='CSS/style.css')}}">
    {%block head_content%}
    {%endblock%}
</head>
<body>
    <header class="header">
        <h1 class="header__logo"><a href="{{ url_for('habits.habitos')}}" class="header__link">Habits</a></h1>
        {% if "novo" not in request.endpoint and "deleta" not in request.endpoint%}
            <div class="header__link">
                <a href="{{ url_for('habits.novohabito')}}" class="header__link__add">Add</a>
                <a href="{{ url_for('habits.deletahabito')}}" class="header__link__drop">Drop</a>
            </div>
        {%else%}
            <div class="header__link">
                <a href="{{ url_for('habits.habitos')}}" class="header__link__back">Back</a>
            </div>
        {% endif %}
    </header>
    <main class="main">
        <section class="dates">
            {%for date in date_range(selected_date)%}
                <a 
                class="dates__link {{'dates__link--current' if loop.index0 ==3 else''}}"
                href="{{url_for('habits.habitos', date=date)}}"
                >
                    <time class="date" datetime="{{date}}">
                        <span>{{date.strftime("%a")}}</span>
                        <span>{{date.strftime("%d")}}</span>
                    </time>
                </a>
            {%endfor%}
        </section>
        {%block main_content%}
        {%endblock%}
        {%block content%}
        {%endblock%}
        {%block content2%}
        {%endblock%}
    </main>
</body>
</html>

templates/drop.html
{% extends 'base.html'%}
{% import 'macros.jinja2' as macros%}

{%block content2%}
<section class="drop__section">
{%for habit in habits%}
{% set drop = habit["_id"] in dropped%}
    {% if drop%}
        <form method="POST" class="drop__form" action="{{url_for('habits.deletahabito')}}">
            <input type="hidden" name="habitId" value="{{habit['_id']}}" />
            <input type="hidden" name="date" value="{{selected_date}}" />
            <input type="hidden" name="confirmation" value="S" />
            <button type="submit" class="drop__selected">
                <span>
                    {{habit["Nome"]}}
                </span>
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="drop__icon" viewBox="0 0 512 512">
                    <path d="M448 256c0-106-86-192-192-192S64 150 64 256s86 192 192 192 192-86 192-192z" fill="none"
                    stroke="currentColor" stroke-miterlimit="10" stroke-width="32" />
                    <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"
                    d="M320 320L192 192M192 320l128-128" />
                    </svg>
                </span>
            </button>
        </form>
    {% else %}
        <form method="POST" class="drop__form" action="{{url_for('habits.deletahabito')}}">
            <input type="hidden" name="habitId" value="{{habit['_id']}}" />
            <input type="hidden" name="date" value="{{selected_date}}" />
            <input type="hidden" name="confirmation" value="U" />
            <button type="submit" class="drop__unselected">
                <span>
                    {{habit["Nome"]}}
                </span>
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="drop__icon" viewBox="0 0 512 512">
                    <path d="M448 256c0-106-86-192-192-192S64 150 64 256s86 192 192 192 192-86 192-192z" fill="none"
                    stroke="currentColor" stroke-miterlimit="10" stroke-width="32" />
                    <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"
                    d="M320 320L192 192M192 320l128-128" />
                    </svg>
                </span>
            </button>
        </form>
{% endif %}
{%endfor%}
<form method="POST" class="confirm__buton" action="{{url_for('habits.deletahabito')}}">
    <input type="hidden" name="confirmation" value="Y" />
    <button type="submit" class="confirm__button">Confirm</button>
</form>
</section>
{%endblock%}

templates/habits.html
{% extends 'base.html'%}
{% import 'macros.jinja2' as macros%}

{%block main_content%}
    <section class="habit-list">
        {%for habit in habits%}
            {% set completed = habit["_id"] in completions%}
            {% if completed%}
                <div class="habit completed">
                    <p class="habit__name">
                    {{habit["Nome"]}}
                    </p>
                    <p>
                        <svg width="35px" height="35px" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect width="48" height="48" fill="white" fill-opacity="0.01"/>
                        <path d="M14 24L15.25 25.25M44 14L24 34L22.75 32.75" stroke="#000000" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M4 24L14 34L34 14" stroke="#000000" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </p>
                </div>
            {% else %}
                {%if habit['Ativo']%}
                    <div class="habit">
                        <form method="POST" class="habit__form" action="{{url_for('habits.complete')}}">
                            <input type="hidden" name="habitId" value="{{habit['_id']}}"/>
                            <input type="hidden" name="date" value="{{selected_date}}"/>
                            <button type="submit" class="habit__button">
                                {{habit["Nome"]}}
                            </button>                        
                        </form>
                    </div>
                {%endif%}
            {% endif %}
        {%endfor%}
    </section>
{%endblock%}

templates/not-found.html
    <h1 class="erro">404 This page was not found.</h1>
    <p class="erro_fr">Please write above what you where trying to do:</p>
    <form class="form" method="POST">
        <textarea class="form__input" id="report" name="report" row ="3" placeholder="Describe on your words"></textarea>
        <button class="form__button" type="submit">Report</button>
    </form>